name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo on the runner
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v

  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job triggered by a ${{ github.event_name }} event is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "This job's status is ${{ job.status }}."
